### PR TITLE
Adding simple docker compose file

### PR DESCRIPTION
**Pull request by ghost**
Hi,

just adding a very plain simple docker-compose file, which I often find more readable and more extensible, especially for those guys who are new to docker.

### CODE REVIEW

**Comment by clebert** [comment]
Thanks for your contribution.

Could you change the message so that the commit is accepted by the linter?
`chore: adding simple docker compose file`

I will document the use of Docker compose next week.

**Comment by ghost** [comment]
Hi Clebert, 

at first thanks for making this repo, it seems really promising and a former colleague of you pointed me here :)

I will change the commit message and if you like, I can also extend the documentation.

**Comment by clebert** [comment]
Probably Lars? :)

I use standard version to automatically generate a changelog. For this, the commit messages must be in a special format. Here is the commitizen config: https://github.com/clebert/cybernaut/blob/master/.cz-config.js

I would be glad about an extension of the documentation. I will be online again in a few days and could then accept the pull request.

**Comment by ghost** [comment]
Yep ;)

I'll see what I can do by the beginning of the next week and add some short extention for documentation as well.

Best

**Pull request merged**
